# Generated by Django 3.0.8 on 2020-10-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(default='SOME STRING', max_length=50)),
                ('Email_id', models.EmailField(max_length=25)),
                ('Employee_id', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=20)),
                ('Domain', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Employee_table',
            },
        ),
    ]
